arb-dir: lib/l10n
template-arb-file: intl_en.arb
output-localization-file: app_localization.dart
output-class: AppLocalizations
synthetic-package: false
nullable-getter: false
preferred-supported-locales:
  - en
  - cs
