name: guess_the_toilet
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  auto_route_generator: ^9.0.0
  auto_route: ^9.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.jpg" # Path to your logo
  adaptive_icon_foreground: "assets/icon/icon.jpg" # Optional for Android adaptive icons
  adaptive_icon_background: "#FFFFFF" # Change to match your design
  # flutter pub run flutter_launcher_icons:main - to use the changes

flutter:
  uses-material-design: true
  assets:
    - assets/icon/icon.jpg
