name: guess_the_toilet
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  auto_route_generator: ^9.0.0
  auto_route: ^9.2.2
  flutter_native_splash: ^2.4.4
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  flame: ^1.25.0
  flutter_dotenv: ^5.2.1
  supabase_flutter: ^2.8.3
  flutter_svg: ^2.0.17
  flame_audio: ^2.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/icon.png" # Path to your icon
  # flutter pub run flutter_launcher_icons:main - to use the changes

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/icon/icon.png
    - assets/images/
    - .env
    - assets/icons/
  fonts:
    - family: Lexend
      fonts:
        - asset: assets/fonts/Lexend-VariableFont_wght.ttf
